#!/bin/sh
set -e

case "$1" in
	configure)
		update-rc.d emmiUpdate start 51 S .
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	triggered)
		/usr/lib/emmi/emmi-update/update-manager.py
	;;
	*)
		echo "postinst called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0

